# Generated by Django 2.2.12 on 2021-03-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcles',
            new_name='Article',
        ),
    ]
